version: '3.9'

services:
  app:
    container_name: 'api'
    build:
      context: .
      dockerfile: Dockerfile
    image: recommender_system:local
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app/
    # depends_on:
    #   - tensorflow-serving
    networks:
      - api-networks
  tensorflow-serving:
    container_name: predict
    image: bitnami/tensorflow-serving:latest
    ports:
      - 8501:8501
    volumes:
      - 'data:/bitnami'
      - './conf:/bitnami/tensorflow-serving/conf/'
      - './models/rps_model:/bitnami/model-data'
    expose:
      - 8501
    environment:
      - TENSORFLOW_SERVING_MODEL_NAME=rps_model
    networks:
      - api-networks
volumes:
  data:
    driver: local
networks:
  api-networks:
    driver: bridge